blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.blogList, name='blog-list'),
    path('blog/<int:pk>', views.blogDetail, name='blog-detail'),
    path('bloggers/', views.bloggersList, name='bloggers-list'),
    path('blogger/<int:bloggerId>', views.bloggerDetail, name='blogger-details'),

]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=500, help_text='enter bio', null=True)

    class Meta():
        ordering = ['user', 'bio']

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('blog:blogger-details', args=[str(self.id)])


class Blog(models.Model):
    title = models.CharField(
        max_length=200, help_text='Title for the blog post')
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    post_date = models.DateField(null=False, blank=False)
    blog_post = models.TextField(max_length=1000, help_text='write your blog')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-detail', args=[str(self.id)])


class Comment(models.Model):
    comment_text = models.TextField(
        max_length=500, help_text='Enter a comment')
    post_date = models.DateTimeField(auto_now_add=True)
    commenter = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta():
        ordering = ['-post_date']

    def __str__(self):
        return self.comment_text

blog/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from blog.models import Comment


class blogComment(forms.Form):
    blog_comment = forms.CharField(widget=forms.Textarea(
        attrs={'style': 'height : 50px; width : 400px',
               'placeholder': 'Enter Your comment'}),
        error_messages={
        'required': 'Please enter a comment'},
        label='',
        max_length=500)

    def clean_data(self):
        return self.cleaned_data['blog_comment']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']
        widgets = {
            'comment_text': Textarea(attrs={'cols': 7, 'rows': 2}),
        }


class deleteComment(forms.Form):
    delete = forms.CharField()

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from blog.models import Author, Blog, Comment
from django.http import HttpResponseRedirect
from blog.forms import CommentForm, deleteComment
from django.contrib.auth.decorators import login_required
from django.urls import reverse


def index(request):
    num_blogs = Blog.objects.count()
    num_bloggers = Author.objects.count()
    num_comments = Comment.objects.count()

    context = {
        'num_blogs': num_blogs,
        'num_bloggers': num_bloggers,
        'num_comments': num_comments
    }
    return render(request, 'index.html', context=context)


def blogList(request):
    blogs = Blog.objects.all()
    context = {
        'blogs': blogs
    }
    return render(request, 'blog/blog_list.html', context=context)


def blogDetail(request, pk):

    blog = get_object_or_404(Blog, pk=pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        delete_comment_form = deleteComment(request.POST)

        if comment_form.is_valid():
            author = get_object_or_404(Author, pk=request.user.id)
            comment = Comment()
            comment.comment_text = comment_form.save(commit=False)
            comment.blog = blog
            comment.commenter = author
            comment.save()
            return HttpResponseRedirect(reverse('blog:blog-detail', kwargs={'pk': pk}))

        if delete_comment_form.is_valid():
            comment_id = request.POST['comment_id']
            comment = get_object_or_404(Comment, pk=comment_id)
            comment.delete()
            return HttpResponseRedirect(reverse('blog:blog-detail', kwargs={'pk': pk}))
    else:
        comments = Comment.objects.filter(blog=blog)
        comment_form = CommentForm()
    context = {
        'blog': blog,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/blog_details.html', context=context)


def bloggersList(request):
    bloggers = Author.objects.all()
    context = {
        'bloggers': bloggers
    }
    return render(request, 'blog/bloggers_list.html', context=context)


def bloggerDetail(request, bloggerId):
    blogger = get_object_or_404(Author, pk=bloggerId)
    blogs = Blog.objects.filter(author=blogger)

    context = {
        'blogger': blogger,
        'blogs': blogs
    }
    return render(request, 'blog/blogger_detail.html', context=context)

blog/templates/basic_form.html
{% load widget_tweaks %}
{% for field in form %}
<div class="form-group">
  {{ field.label_tag }}
  {% render_field field class="form-control" %}
  {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
  {% endif %}
</div>
{% endfor %}

blog/templates/basic_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}

        <ul class="sidebar-nav">
          <li><a href="{% url 'blog:index' %}">Home</a></li>
          <li><a href="{% url 'blog:blog-list' %}">All Blogs</a></li>
          <li><a href="{% url 'blog:bloggers-list' %}">All Bloggers</a></li>
        </ul>
        <hr>
        {% if user.is_authenticated %}
        <p>User: {{ user.get_username }}</p> 
         <a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
        {% else %}
         <a href="{% url 'login'%}?next={{request.path}}">Login</a>
        {% endif %}

        {% endblock %}
      </div>
      <div class="col-sm-10 ">

        {% block content %} {% endblock %}

        <!-- {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %} -->
      </div>
    </div>
  </div>
</body>

</html>

blog/templates/blog/blog_details.html
{% extends "basic_layout.html" %}

{% block content %}
{% if blog %}
<h1>{{blog.title}}</h1>

<p>By {{ blog.author }} on <strong>{{ blog.post_date }}</strong></p>
<hr>
<p>{{blog.blog_post}}</p>

{% if comments %}
<h4>Comments:</h4>
{% for comment in comments %}
<hr>
<p><strong>{{ comment.commenter }}</strong> : {{ comment.comment_text }} - {{ comment.post_date }}</p>
{% if user == comment.commenter %}
<form action="" method="post">
  {% csrf_token %}
  <input type="hidden" name="comment_id" value="{{ comment.id }}">
  <input type="submit" name="delete" value="delete">
</form>
{% endif %}

{% endfor %}
{% else %}
<hr>

<h5>This blog doesnt have any comments yet :( </h5>
{% endif %}
<hr>
  {% if user.is_authenticated %}
  <form action="" method="post">
    {% csrf_token %}
    {% include "../basic_form.html" with form=comment_form %}
    <input type="submit" class="btn btn-primary" value="Post Comment">
  </form>
  {% else %}
    <p>login to post comments</p>
  {% endif %}


{% endif %}
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'basic_layout.html' %}

{% block content %}
<h1>Blog List</h1>
 {% if blogs %}
  <ul>
  {% for blog in blogs %}
    <li>
      <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> by {{ blog.author }}
    </li>

{% endfor %}
</ul>
{% else %}
<p>No Blogs found </p>

{% endif %}
{% endblock %}

blog/templates/blog/blogger_detail.html
{% extends "basic_layout.html"%}

{% block content %}
{% if blogger %}
  <h2>{{ blogger.user }}</h2>
  <p>{{ blogger.bio }}</p>
  <hr>

  {% if blogs %}
  <ul>
    {% for blog in blogs %}
      <li><a href="{{ blog.get_absolute_url }}">{{blog.title}}</a></li>
    {% endfor %}
  </ul>

    {% else %}
    <p>This user has not posted any blogs yet :( </p>

  {% endif %}
{% endif %}

{% endblock%}

blog/templates/blog/bloggers_list.html
{% extends 'basic_layout.html' %}

{% block content %}
<h1>Bloggers List</h1>
 {% if bloggers %}
  <ul>
  {% for blogger in bloggers %}
    <li>
      <a href="{{ blogger.get_absolute_url }}">{{ blogger.user }}</a>
    </li>

{% endfor %}
</ul>
{% else %}
<p>No Bloggers found </p>

{% endif %}
{% endblock %}

blog/templates/index.html
{% extends "basic_layout.html" %}

{% block content %}
<h1>Blog Home</h1>
<p>Welcome to Blogged a website developed using <em>Django 2</em>!</p>
<h3>The Blog has the following record counts:</h3>
<ul>
  <li><strong>Blogs:</strong> {{ num_blogs }}</li>
  <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
  <li><strong>Total Comments:</strong> {{ num_comments }}</li>
</ul>

<!-- <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p> -->
{% endblock %}